The `oauth2_provider` Django app from Django OAuth Toolkit is no longer loaded as itâ€™s no longer used.
